
DATABASE:
  #POSTGRE
  TYPE: POSTGRESQL
  HOST: 10.220.13.77
  PORT: 5432
  DATABASE: pdi
  USERNAME: pdi_user
  PASSWORD: PWD_011
  SCHEMA: Common
#  TYPE: POSTGRESQL
#  HOST: localhost
#  PORT: 5432
#  DATABASE: test
#  USERNAME: postgres
#  PASSWORD: 123456
#  SCHEMA: Common

API:
  ENVIRONMENT: DEVELOPMENT
  NAME: Pdi Application(Python Data Integrator)
  IS_DEBUG: False
  PORT: 7100
  SECRET_KEY: s4GGU7jFnKjgu1LsK7fUdxOp1DUSQ-PVgvr28rBNAHM=
